### ISSUE TITLE
[BUG] Null pointer listing regions/zones in gcp

### ISSUE THREAD

**Issue by laferrieren** [hortonworks/cloudbreak#4077]
# Bug Report
On gcp, cloudbreak appears to run into a null pointer when trying to create a new cluster on `2.7.(1|2)`.  I tried different service accounts and different key formats and on multiple servers and ran into same issue.  It doesn't appear to be a networking issue, as it can connect to aws for starting cluster, with aws keys.

I added everything below that is asked for, by default, when creating an issue.  Let me know if anything else would help out

# info
## cbd version
```local version:2.7.2
latest release:2.7.2
docker images:
 hortonworks/haveged:1.1.0
 hortonworks/socat:1.0.0
 hortonworks/logspout:v3.2.2
 hortonworks/logrotate:1.0.1
 hortonworks/cbd-smartsense:0.13.2
 hortonworks/cloudbreak-uaa:3.6.5-pgupdate
 hortonworks/cloudbreak:2.7.2
 hortonworks/hdc-auth:2.7.2
 hortonworks/hdc-web:2.7.2
 hortonworks/cloudbreak-autoscale:2.7.2
```
## host platform
running a machine on gcp, `rhel-7-v20181011` as a base image

## steps to reproduce
followed guide https://docs.hortonworks.com/HDPDocuments/Cloudbreak/Cloudbreak-2.7.2/content/gcp-launch/index.html
using image `rhel-7-v20181011`

* created service account with roles listed in doc
* uploaded credentials, and clicked created cluster (tried with both json/p12, and with two different projects)
while trying to load region/zone info there is a null pointer in the backend and errors out

## error
```
cloudbreak_1   | 2018-10-23 17:40:05,984 [reactorDispatcher-14] accept:46 WARN  c.s.c.c.h.GetRegionsV2Handler - [owner:spring] [type:springLog] [id:] [name:] [flow:] [tracking:] Could not get regions from the cloud provider due to:
cloudbreak_1   | java.lang.NullPointerException: null
cloudbreak_1   |    at com.sequenceiq.cloudbreak.cloud.gcp.t.regions(GcpPlatformResources.java:145)
cloudbreak_1   |    at com.sequenceiq.cloudbreak.cloud.gcp.GcpPlatformResources$$FastClassBySpringCGLIB$$7f2f245d.invoke(<generated>)
cloudbreak_1   |    at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:204)
cloudbreak_1   |    at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:738)
cloudbreak_1   |    at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:157)
cloudbreak_1   |    at org.springframework.cache.interceptor.CacheInterceptor$1.invoke(CacheInterceptor.java:52)
cloudbreak_1   |    at org.springframework.cache.interceptor.CacheAspectSupport.invokeOperation(CacheAspectSupport.java:345)
cloudbreak_1   |    at org.springframework.cache.interceptor.CacheAspectSupport.execute(CacheAspectSupport.java:408)
cloudbreak_1   |    at org.springframework.cache.interceptor.CacheAspectSupport.execute(CacheAspectSupport.java:327)
cloudbreak_1   |    at org.springframework.cache.interceptor.CacheInterceptor.invoke(CacheInterceptor.java:61)
cloudbreak_1   |    at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
cloudbreak_1   |    at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:673)
cloudbreak_1   |    at com.sequenceiq.cloudbreak.cloud.gcp.GcpPlatformResources$$EnhancerBySpringCGLIB$$c88fe5fa.regions(<generated>)
cloudbreak_1   |    at com.sequenceiq.cloudbreak.cloud.handler.GetRegionsV2Handler.accept(GetRegionsV2Handler.java:41)
cloudbreak_1   |    at com.sequenceiq.cloudbreak.cloud.handler.GetRegionsV2Handler.accept(GetRegionsV2Handler.java:20)
cloudbreak_1   |    at com.sequenceiq.cloudbreak.cloud.handler.GetRegionsV2Handler$$FastClassBySpringCGLIB$$8867751c.invoke(<generated>)
cloudbreak_1   |    at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:204)
cloudbreak_1   |    at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:738)
cloudbreak_1   |    at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:157)
cloudbreak_1   |    at org.springframework.aop.framework.adapter.MethodBeforeAdviceInterceptor.invoke(MethodBeforeAdviceInterceptor.java:52)
cloudbreak_1   |    at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
cloudbreak_1   |    at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:92)
cloudbreak_1   |    at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
cloudbreak_1   |    at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:673)
cloudbreak_1   |    at com.sequenceiq.cloudbreak.cloud.handler.GetRegionsV2Handler$$EnhancerBySpringCGLIB$$14b4ef71.accept(<generated>)
cloudbreak_1   |    at reactor.bus.EventBus$3.accept(EventBus.java:317)
cloudbreak_1   |    at reactor.bus.EventBus$3.accept(EventBus.java:310)
cloudbreak_1   |    at reactor.bus.routing.ConsumerFilteringRouter.route(ConsumerFilteringRouter.java:72)
uluwatu_1      | 2018-10-23T17:40:05.999Z INFO [owner:82fa8471-3e37-43d8-a836-6958a4236e88] [email: ops@tamr.com] [tracking: eb4c65e9-4b91-48f8-a464-69339b541b84] 10.30.0.12 - POST /cloudbreak/v2/connectors/regions HTTP/1.1 400 533.986 ms [103]
cloudbreak_1   |    at reactor.bus.routing.TraceableDelegatingRouter.route(TraceableDelegatingRouter.java:51)
cloudbreak_1   |    at reactor.bus.EventBus.accept(EventBus.java:591)
cloudbreak_1   |    at reactor.bus.EventBus.accept(EventBus.java:63)
cloudbreak_1   |    at reactor.core.dispatch.AbstractLifecycleDispatcher.route(AbstractLifecycleDispatcher.java:160)
cloudbreak_1   |    at reactor.core.dispatch.MultiThreadDispatcher$MultiThreadTask.run(MultiThreadDispatcher.java:74)
cloudbreak_1   |    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
cloudbreak_1   |    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
cloudbreak_1   |    at java.lang.Thread.run(Thread.java:748)
```
link it in gist: https://gist.github.com/laferrieren/b5872212b431ff67c38646c8f3519e71

**Comment by laferrieren** [comment]
This appears to have been caused from the google apis erroring out.  Coming back to same cloudbreak instance 2 days later, without modifying config or networking it works fine.
